# ackermann.yaml
# 阿克曼车平台配置

controller_ros:
  ros__parameters:
    platform:
      type: "ackermann"

controller:
  system:
    platform: "ackermann"
  mpc:
    horizon: 20
    dt: 0.1
    v_max: 2.0
    omega_max: 0.8
